version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    assignees:
      - xbzz1018
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      python-minor-patch:
        update-types:
          - minor
          - patch
